# iOS CircleCI 2.0 configuration file
#

version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.0.0"

    steps:
      - checkout

      - run:
          name: Clone KitBridge
          command: git clone https://github.com/alfwatt/KitBridge.git ../KitBridge

      - run:
          name: Build SparkKit (iOS)
          command: xcodebuild -scheme "SparkKit (iOS)"

      - run:
          name: Build SparkKit (macOS)
          command: xcodebuild -scheme "SparkKit (macOS)"

      - run:
          name: Build Sparky (iOS)
          command: xcodebuild -scheme "Sparky (iOS)" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - run:
          name: Build Sparky (macOS)
          command: xcodebuild -scheme "Sparky (macOS)" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

#      - run:
#          name: Build Sparky TV
#          command: xcodebuild -scheme "Sparky TV" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
